apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: application-api
  name: application-api
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: application-api
status:
  loadBalancer: {}
